Add workflow file with exit 1

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -14,7 +14,7 @@ jobs:
     steps:
       - name: Failed step
         run: |
-          echo "I will succeed"
-          exit 0
+          echo "I will fail"
+          exit 1
       - name: Say goodbye
         run: echo "Goodbye!"
